# Generated by Django 5.0.14 on 2026-02-09 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_checked', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-joined_at']},
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='uniq_user_household',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('household', 'user')},
        ),
        migrations.AddField(
            model_name='household',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_list_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_list_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_shopping_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='core.household'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shoppinglist'),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglist',
            unique_together={('household', 'name')},
        ),
    ]
