# Generated by Django 5.0.14 on 2026-02-09 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listitem_shoppinglist_alter_household_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='aisle',
            field=models.CharField(choices=[('produce', 'Fruits & légumes'), ('fresh', 'Frais'), ('meatfish', 'Viande & poisson'), ('grocery', 'Épicerie'), ('frozen', 'Surgelés'), ('bakery', 'Boulangerie'), ('drinks', 'Boissons'), ('hygiene', 'Hygiène'), ('home', 'Maison'), ('other', 'Autres')], default='grocery', max_length=20),
        ),
        migrations.CreateModel(
            name='ReferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('aisle', models.CharField(choices=[('produce', 'Fruits & légumes'), ('fresh', 'Frais'), ('meatfish', 'Viande & poisson'), ('grocery', 'Épicerie'), ('frozen', 'Surgelés'), ('bakery', 'Boulangerie'), ('drinks', 'Boissons'), ('hygiene', 'Hygiène'), ('home', 'Maison'), ('other', 'Autres')], default='grocery', max_length=20)),
                ('default_quantity', models.CharField(blank=True, max_length=50)),
                ('default_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_reference_items', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_items', to='core.household')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.AddField(
            model_name='listitem',
            name='reference_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items', to='core.referenceitem'),
        ),
    ]
