# Generated by Django 5.2.5 on 2026-02-14 14:48

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fix_default_note_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='referenceitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='listitem',
            name='aisle',
            field=models.CharField(choices=[('produce', 'Fruits & légumes'), ('fresh', 'Frais'), ('meatfish', 'Viande & poisson'), ('grocery', 'Épicerie'), ('frozen', 'Surgelés'), ('bakery', 'Boulangerie'), ('drinks', 'Boissons'), ('hygiene', 'Hygiène'), ('home', 'Maison'), ('other', 'Autres')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='reference_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.referenceitem'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['shopping_list', 'is_checked'], name='core_listit_shoppin_89a953_idx'),
        ),
        migrations.AddIndex(
            model_name='referenceitem',
            index=models.Index(fields=['household', 'is_active'], name='core_refere_househo_c01cae_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['household', '-created_at'], name='core_shoppi_househo_5e7673_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('household', 'user'), name='unique_membership'),
        ),
        migrations.AddConstraint(
            model_name='referenceitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('household'), name='unique_reference_ci'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='unique_list_per_household'),
        ),
        migrations.RemoveField(
            model_name='referenceitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='referenceitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='created_by',
        ),
    ]
