# Generated by Django 5.2.5 on 2026-02-14 16:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='listitem',
            name='aisle',
            field=models.CharField(choices=[('produce', 'Fruits & légumes'), ('fresh', 'Frais'), ('meatfish', 'Viande & poisson'), ('grocery', 'Épicerie'), ('frozen', 'Surgelés'), ('bakery', 'Boulangerie'), ('drinks', 'Boissons'), ('hygiene', 'Hygiène'), ('home', 'Maison'), ('other', 'Autres')], default='grocery', max_length=20),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=120)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.household')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.shoppinglist')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('is_price_unknown', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='core.listitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.receipt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['household', '-purchased_at'], name='core_receip_househo_148b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['shopping_list', '-purchased_at'], name='core_receip_shoppin_bb7c36_idx'),
        ),
        migrations.AddConstraint(
            model_name='receiptitem',
            constraint=models.UniqueConstraint(fields=('receipt', 'list_item'), name='unique_receipt_line'),
        ),
    ]
