# Generated by Django 5.2.5 on 2026-02-14 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_household_created_by_alter_listitem_aisle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AlterModelOptions(
            name='receiptitem',
            options={'ordering': ['position', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='referenceitem',
            name='unique_reference_ci',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='status',
        ),
        migrations.AddField(
            model_name='listitem',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_list_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='reference_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items', to='core.referenceitem'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.shoppinglist'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='list_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_item', to='core.listitem'),
        ),
        migrations.AddIndex(
            model_name='referenceitem',
            index=models.Index(fields=['household', 'is_selected'], name='core_refere_househo_c8f7d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='referenceitem',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='unique_reference_ci'),
        ),
    ]
