# Generated by Django 5.2.11 on 2026-02-15 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_shoppinglist_unique_list_per_household_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='household',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='referenceitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique_membership',
        ),
        migrations.RemoveConstraint(
            model_name='receiptitem',
            name='unique_receipt_line',
        ),
        migrations.RemoveConstraint(
            model_name='referenceitem',
            name='unique_reference_ci',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_shopping_list_per_household',
        ),
        migrations.RemoveIndex(
            model_name='listitem',
            name='core_listit_shoppin_89a953_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='core_receip_househo_148b2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='core_receip_shoppin_bb7c36_idx',
        ),
        migrations.RemoveIndex(
            model_name='referenceitem',
            name='core_refere_househo_c01cae_idx',
        ),
        migrations.RemoveIndex(
            model_name='referenceitem',
            name='core_refere_househo_c8f7d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='shoppinglist',
            name='core_shoppi_househo_5e7673_idx',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='total_amount',
            new_name='paper_total',
        ),
        migrations.RenameField(
            model_name='receiptitem',
            old_name='price',
            new_name='actual_price',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='reference_item',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'household')},
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='is_price_unknown',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='created_by',
        ),
        migrations.AddField(
            model_name='listitem',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='household',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='households_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listitem',
            name='aisle',
            field=models.CharField(choices=[('grocery', 'Épicerie'), ('fruits_veg', 'Fruits & légumes'), ('meat_fish', 'Boucherie / Poissonnerie'), ('dairy', 'Crèmerie'), ('frozen', 'Surgelés'), ('household', 'Entretien'), ('other', 'Autre')], default='grocery', max_length=30),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_list_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='list_items_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listitem',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Propriétaire'), ('member', 'Membre')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='list_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_line', to='core.listitem'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='aisle',
            field=models.CharField(choices=[('grocery', 'Épicerie'), ('fruits_veg', 'Fruits & légumes'), ('meat_fish', 'Boucherie / Poissonnerie'), ('dairy', 'Crèmerie'), ('frozen', 'Surgelés'), ('household', 'Entretien'), ('other', 'Autre')], default='grocery', max_length=30),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='default_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='default_quantity',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='household',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='core.household'),
        ),
        migrations.AlterUniqueTogether(
            name='referenceitem',
            unique_together={('household', 'name')},
        ),
        migrations.RemoveField(
            model_name='membership',
            name='joined_at',
        ),
    ]
