# Generated by Django 5.2.11 on 2026-02-15 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_household_options_alter_listitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='core.household'),
        ),
    ]
