# Generated by Django 5.2.11 on 2026-02-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shoppinglist_closed_at_alter_shoppinglist_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Propriétaire'), ('member', 'Membre')], default='member', max_length=20, null=True),
        ),
    ]
