# Generated by Django 5.2.5 on 2026-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_membership_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='referenceitem',
            name='default_quantity',
        ),
        migrations.AddField(
            model_name='listitem',
            name='qty_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='unit',
            field=models.CharField(choices=[('unit', 'Unité'), ('kg', 'Kg'), ('g', 'g'), ('l', 'L'), ('ml', 'mL'), ('pack', 'Pack')], default='unit', max_length=20),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='default_qty_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='default_unit',
            field=models.CharField(choices=[('unit', 'Unité'), ('kg', 'Kg'), ('g', 'g'), ('l', 'L'), ('ml', 'mL'), ('pack', 'Pack')], default='unit', max_length=20),
        ),
    ]
