# Generated by Django 5.2.5 on 2026-02-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_listitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='aisle',
            field=models.CharField(choices=[('al_fruits_veg', 'Alimentaire ▸ Fruits & légumes frais'), ('al_bakery', 'Alimentaire ▸ Pains & viennoiseries'), ('al_staples', 'Alimentaire ▸ Œufs, pâtes, riz, conserves'), ('al_dairy', 'Alimentaire ▸ Produits laitiers & fromages'), ('al_meat', 'Alimentaire ▸ Viandes, charcuteries'), ('al_fish', 'Alimentaire ▸ Poissons & produits de la mer'), ('al_grocery', 'Alimentaire ▸ Épicerie salée & sucrerie'), ('al_ready', 'Alimentaire ▸ Plats préparés & frais réfrigérés'), ('al_frozen', 'Alimentaire ▸ Produits surgelés'), ('dr_soft', 'Boissons ▸ Boissons non alcoolisées (eau, sodas, jus…)'), ('dr_alcohol', 'Boissons ▸ Vins, bières, spiritueux'), ('hy_body', 'Hygiène & beauté ▸ Soins corporels'), ('hy_daily', 'Hygiène & beauté ▸ Hygiène quotidienne'), ('hy_hair', 'Hygiène & beauté ▸ Parfums et soins capillaires'), ('nf_promo', 'Non alimentaire ▸ Offres hebdomadaires / promotions')], default='al_fruits_veg', max_length=40),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='aisle',
            field=models.CharField(choices=[('al_fruits_veg', 'Alimentaire ▸ Fruits & légumes frais'), ('al_bakery', 'Alimentaire ▸ Pains & viennoiseries'), ('al_staples', 'Alimentaire ▸ Œufs, pâtes, riz, conserves'), ('al_dairy', 'Alimentaire ▸ Produits laitiers & fromages'), ('al_meat', 'Alimentaire ▸ Viandes, charcuteries'), ('al_fish', 'Alimentaire ▸ Poissons & produits de la mer'), ('al_grocery', 'Alimentaire ▸ Épicerie salée & sucrerie'), ('al_ready', 'Alimentaire ▸ Plats préparés & frais réfrigérés'), ('al_frozen', 'Alimentaire ▸ Produits surgelés'), ('dr_soft', 'Boissons ▸ Boissons non alcoolisées (eau, sodas, jus…)'), ('dr_alcohol', 'Boissons ▸ Vins, bières, spiritueux'), ('hy_body', 'Hygiène & beauté ▸ Soins corporels'), ('hy_daily', 'Hygiène & beauté ▸ Hygiène quotidienne'), ('hy_hair', 'Hygiène & beauté ▸ Parfums et soins capillaires'), ('nf_promo', 'Non alimentaire ▸ Offres hebdomadaires / promotions')], default='al_fruits_veg', max_length=40),
        ),
    ]
