# Generated by Django 5.2.11 on 2026-02-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_listitem_aisle_alter_referenceitem_aisle'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='referenceitem',
            name='default_unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
